### ISSUE TITLE
why does the FBSE spectrum of ECG is giving a strange response than FFT???

### ISSUE THREAD

**Issue by rsarka34** [tripathy12345/FBSE-EWT#1]
![image](https://github.com/user-attachments/assets/bff74932-5f40-4cc9-b4e4-8c67cffbf034)
why does the FBSE spectrum of ECG is giving a strange response than FFT.

how does the amplitude is negative.. do we have to take absolute value

**Comment by tripathy12345** [comment]
What do you mean by a strange response? 

FFT uses complex exponentials, whereas FBSE uses Bessel functions (real valued only). 

Even for other signals, you will get -ve amplitude value for different order of the Bessel function. 
https://en.wikipedia.org/wiki/Fourier%E2%80%93Bessel_series
Yes, one can take absolute value. FBSE-EWT uses absolute value of FBSE coefficients to design filter bank.
